# Course 1 Week 1 Quiz 1

## Q1: What will be the output of the following code?

In [1]:
import re

string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [2]:
# [ao] means any char a or o

## Q2: Assume a and b are two (20, 20) numpy arrays. The L2-distance (defined above) between two equal dimension arrays can be calculated in python as follows:

In [3]:
import numpy as np

In [13]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

##### Which of the following expressions using this function will produce a different result from the rest?
> l2_dist(a, b)
>
> l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20, 1)))
>
> l2_dist(a.T, b.T)
>
> l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))

In [22]:
c = np.reshape(a,(20*20))

In [23]:
d = np.reshape(a,(20*20, 1))

In [24]:
l2_dist(a,b)

0.0

In [25]:
l2_dist(c,d)

65319.522349753905

In [26]:
l2_dist(a.T,b.T)

0.0

In [27]:
l2_dist(c,c)

0.0

In [0]:
##### So the answer is B, but why?

In [28]:
print(c.shape)
print(d.shape)

# you can see that c is a horizontal array while d is vertical

(400,)
(400, 1)


## Q3: more about the np

In [29]:
# consider the following code:

a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [30]:
print(a1); print(a2); print(a3); print(a4); print(a5)
# one can understand the above code by printing out the answers

[0.34050471 0.08605185 0.44642584 0.97859662]
[[0.24085411]
 [0.50979792]
 [0.17594263]
 [0.04176785]]
[[1 2 3 4]]
[1 2 3]
[1. 2. 3. 4.]


##### Which of the following statements regarding these variables is correct?

> a4.ndim() == 1

> a1.shape == a2.shape

> a5.shape == a1.shape

> a3.shape == a4.shape

In [35]:
# my first guess: C; both being (4, )
print(a5.shape == a1.shape)

True


## Q4: Correct output of the code below:

In [36]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


> Explaination: since new = old; any changes in the new will affect the old

In [44]:
# code to prevent this:

old = np.array([[1, 1, 1], [1, 1, 1]])
new = np.copy(old)
new[0, :2] = 0
print(old)

[[1 1 1]
 [1 1 1]]


## Q5: Given the 6x6 NumPy array r shown below, which of the following options would slice the shaded elements?

In [45]:
a = np.arange(6*6).reshape(6,6)
print(a)
# need to shade 14, 15, 20, 21

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [46]:
a[2:4,2:4]

array([[14, 15],
       [20, 21]])

## Q6: For the given string, which of the following regular expressions can be used to check if the string starts with 'AC'?

In [51]:
import re 
a = 'ACBCAC'
b = 'CBDCAC'

In [53]:
re.findall("^AC",a)

['AC']

In [54]:
re.findall("^AC",b)

[]

## Q7: What will be the output of the variable L after the following code is executed?

In [55]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)

In [58]:
print(result)
print(L)

['A', 'AA', 'AA', 'AA', 'A']
5


##### from the documentation:

> {m,n}

> Causes the resulting RE to match from m to n repetitions of the preceding RE, attempting to match as many repetitions as possible. For example, a{3,5} will match from 3 to 5 'a' characters. Omitting m specifies a lower bound of zero, and omitting n specifies an infinite upper bound. As an example, a{4,}b will match 'aaaab' or a thousand 'a' characters followed by a 'b', but not 'aaab'. The comma may not be omitted or the modifier would be confused with the previously described form.

In [61]:
# trying with other methods
print(re.findall("A{1}",s))
print(re.findall("A{2}",s))
print(re.findall("A{3}",s))

['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A']
['AA', 'AA', 'AA']
['AAA']


## Q8: Which of the following is the correct regular expression to extract all the phone numbers from the following chunk of text:

> Office of Research Administration: (734) 647-6333 | 4325 North Quad
    
> Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205
    
> Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500
    
> Office of the Dean: (734) 647-3576 | 4322 North Quad
    
> UMSI Engagement Center: (734) 763-1251 | 777 North University
    
> Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad

\d{3}\s\d{3}[-]\d{4}

\d{3}[-]\d{3}[-]\d{4}

[(]\d{3}[)]\d{3}[-]\d{4}

[(]\d{3}[)]\s\d{3}[-]\d{4}

In [63]:
a = "Office of Research Administration: (734) 647-6333 | 4325 North Quad"

In [66]:
re.findall("[(]\d{3}[)]\s\d{3}[-]\d{4}", a)

['(734) 647-6333']

## Q9: Which of the following regular expressions can be used to get the domain names (e.g. google.com, www.baidu.com) from the following sentence?

In [67]:
a = "I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything"

In [69]:
# (?<=[https]:\/\/)([A-Za-z0-9.]*)

# (?<=https:\/\/)([A-Za-z0-9.]*)

# (?<=https:\/\/)([.]*)

# (?<=https:\/\/)([A-Za-z0-9]*)

In [74]:
re.findall("(?<=[https]:\/\/)([A-Za-z0-9.]*)",a)

['google.com', 'www.baidu.com']

> ?<= the captured match must be followed by whatever is within the parentheses but that part isn't captured

> [https] includes both http and https

In [71]:
re.findall("(?<=https:\/\/)([A-Za-z0-9.]*)",a)

['google.com']

In [72]:
re.findall("(?<=https:\/\/)([.]*)",a)

['']

In [73]:
re.findall("(?<=https:\/\/)([A-Za-z0-9]*)",a)

['google']

> "." should be included or else the string behind the "." will be skipped

## Q10: The text from the Canadian Charter of Rights and Freedoms section 2 lists the fundamental freedoms afforded to everyone. Of the four choices provided to replace X in the code below, which would accurately count the number of fundamental freedoms that Canadians have?

In [76]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

287


In [81]:
import re
pattern = "(.)"
print(len(re.findall(pattern,text)))

287


> . for all characters

In [79]:
pattern = "[a-d]"
print(len(re.findall(pattern,text)))

40


> [a-d] for all a to d

In [80]:
pattern = "\(.\)"
print(len(re.findall(pattern,text)))

4


> \ recognized what follows "\" (for special characters)